server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    autoindex off;

    location = /playground { return 301 /playground/; }

    location /playground/ { try_files $uri $uri/ =404; }
    location / { try_files $uri $uri/ =404; }
}
