### GET tasks unauthorized

GET {{CLICK_UP_API_ENDPOINT}}/tasks


### GET tasks

GET {{CLICK_UP_API_ENDPOINT}}/tasks
Authorization: {{token_type}} {{access_token}}


### POST task

POST {{CLICK_UP_API_ENDPOINT}}/tasks
Authorization: {{token_type}} {{access_token}}


### GET task

GET {{CLICK_UP_API_ENDPOINT}}/tasks/my-task
Authorization: {{token_type}} {{access_token}}





### GET props unauthorized

GET {{USER_PROPS_API_ENDPOINT}}


### GET props

GET {{USER_PROPS_API_ENDPOINT}}
Authorization: {{token_type}} {{access_token}}


### POST prop with userId

POST {{USER_PROPS_API_ENDPOINT}}
Authorization: {{token_type}} {{access_token}}
Content-Type: application/json; charset=utf-8

{
  "userId": "someone-else"
}


### POST prop primitive

POST {{USER_PROPS_API_ENDPOINT}}
Authorization: {{token_type}} {{access_token}}
Content-Type: application/json; charset=utf-8

{
  "my-primitive": "my value"
}


### POST prop object

POST {{USER_PROPS_API_ENDPOINT}}
Authorization: {{token_type}} {{access_token}}
Content-Type: application/json; charset=utf-8

{
  "my-object": {
    "foo": "bar",
    "baz": null
  }
}


### GET prop

GET {{USER_PROPS_API_ENDPOINT}}/6b52eb64-7d86-4f4d-a9d3-fde6756c3178
Authorization: {{token_type}} {{access_token}}
