[versions]
compose = "1.3.0-rc01"
kommons = "2.5.0"
kotlin = "1.7.21"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.1"
ktor = "2.2.1"
node = "16.0.0"
shadow = "7.1.2"

[libraries]
kommons = { module = "com.bkahlert.kommons:kommons", version.ref = "kommons" }
kommons-test = { module = "com.bkahlert.kommons:kommons-test", version.ref = "kommons" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
