[versions]
aws-lambda-java-core = "1.2.2"
aws-lambda-java-events = "3.11.0"
aws-lambda-java-log4j2 = "1.5.1"
aws-lambda-java-tests = "1.1.1"
aws-sdk-kotlin = "0.19.0-beta"
compose = "1.3.0-rc01"
compose-compiler = "1.4.0-alpha02"
dokka = "1.7.21"
kommons = "2.5.0"
kotlin = "1.7.21"
kotlin-logging = "2.1.23"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.1"
kotest = "5.4.1"
ktor = "2.2.1"
logstash-logback-encoder = "7.2"
mordant = "2.0.0-beta7"
node = "16.0.0"
nebula-release = "16.0.0"
shadow = "7.1.2"

[libraries]
aws-lambda-java-core = { module = "com.amazonaws:aws-lambda-java-core", version.ref = "aws-lambda-java-core" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "aws-lambda-java-events" }
aws-lambda-java-log4j2 = { module = "com.amazonaws:aws-lambda-java-log4j2", version.ref = "aws-lambda-java-log4j2" }
aws-lambda-java-tests = { module = "com.amazonaws:aws-lambda-java-tests", version.ref = "aws-lambda-java-tests" }
aws-sdk-kotlin-s3 = { module = "aws.sdk.kotlin:s3", version.ref = "aws-sdk-kotlin" }
aws-sdk-kotlin-lambda = { module = "aws.sdk.kotlin:lambda", version.ref = "aws-sdk-kotlin" }
aws-sdk-kotlin-dynamodb = { module = "aws.sdk.kotlin:dynamodb", version.ref = "aws-sdk-kotlin" }
kommons = { module = "com.bkahlert.kommons:kommons", version.ref = "kommons" }
kommons-test = { module = "com.bkahlert.kommons:kommons-test", version.ref = "kommons" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlin-logging" }

kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }

mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }



[bundles]
aws-lambda-java = ["aws-lambda-java-core", "aws-lambda-java-events", "aws-lambda-java-log4j2"]
aws-sdk-kotlin = ["aws-sdk-kotlin-s3", "aws-sdk-kotlin-lambda", "aws-sdk-kotlin-dynamodb"]
ktor-js-client = ["ktor-client-core", "ktor-client-js", "ktor-client-auth", "ktor-client-logging", "ktor-client-serialization", "ktor-client-content-negotiation"]

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka:dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nebula = { id = "com.netflix.nebula:nebula-release-plugin", version.ref = "nebula-release" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
