service: hello
frameworkVersion: '3'

# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
provider:
  name: aws
  runtime: java11
  architecture: arm64

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 1000
  deploymentMethod: direct
  tracing:
    apiGateway: true
    lambda: true

  environment:
    DOMAIN: ${self:custom.customDomain.domainName}
    STAGE: ${self:provider.stage}
    DYNAMODB_PROPS_TABLE: ${self:service}-props-${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Get*
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-props-${sls:stage}
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource:
            - '*'

package:
  artifact: build/libs/serverless-all.jar

functions:
  handleRoot:
    handler: com.bkahlert.hello.api.RootHandler
    events:
      - httpApi:
          path: /
          method: get
  handleClickUp:
    handler: com.bkahlert.hello.api.clickup.ClickUpHandler
    events:
      - httpApi:
          path: /clickup/{path+}
          method: any
    environment:
      CLICKUP_URL: https://api.clickup.com/api/v2
      CLICKUP_API_TOKEN: ${ssm:/clickup_api_token}
      CLICKUP_CLIENT_ID: ${ssm:/clickup_client_id}
      CLICKUP_CLIENT_SECRET: ${ssm:/clickup_client_secret}
  getProp:
    handler: com.bkahlert.hello.api.props.PropsHandler
    events:
      - httpApi:
          path: /props/{id}
          method: get
  setProp:
    handler: com.bkahlert.hello.api.props.PropsHandler
    events:
      - httpApi:
          path: /props/{id}
          method: post

custom:
  domains:
    prod:
      domainName: hello.aws.choam.de
      certificateName: hello.aws.choam.de
    dev:
      domainName: hello-dev.aws.choam.de
      certificateName: hello-dev.aws.choam.de

  # Amazon Certificate Manager
  customCertificate:
    region: us-east-1 # required for CloudFront
    hostedZoneNames: aws.choam.de.
    certificateName: ${self:custom.domains.${self:provider.stage}.certificateName}
    subjectAlternativeNames:
      - "*.${self:custom.domains.${self:provider.stage}.certificateName}"

  # Route53
  customDomain:
    domainName: "api.${self:custom.domains.${self:provider.stage}.domainName}"
    certificateName: ${self:custom.domains.${self:provider.stage}.certificateName}
    createRoute53Record: true # creates A and AAAA records
    autoDomain: true # runs as part of deploy and remove

    apiType: http
    basePath: ''
    hostedZoneId: Z01449492IRUS6954XDJ4
    endpointType: REGIONAL

  s3Sync:
    - bucketName: ${self:custom.domains.${self:provider.stage}.domainName}
      localDir: build/web-app
    # TODO add dependency to :web-app:jsBrowserProductionWebpack, see https://docs.gradle.org/current/userguide/cross_project_publications.html
  # TODO filter application.dev.json

  # TODO create CloudFront distribution with alternate domain name ${self:custom.domains.${self:provider.stage}.domainName}
  # TODO create CNAME for ${self:custom.domains.${self:provider.stage}.domainName} pointing to distribution domain name

# see https://www.serverless.com/framework/docs/providers/aws/guide/resources
resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.domains.${self:provider.stage}.domainName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
    PropsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-props-${sls:stage}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: propId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: propId
            KeyType: RANGE
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"


plugins:
  - serverless-s3-sync
  - serverless-domain-manager
  - serverless-certificate-creator
