AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Minimal example of an AWS Lambda function with Kotlin, Java 11, and Gradle 7 using the base and base-test module.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/libs/minimal-base-all.jar
      Handler: com.example.aws.LambdaHandler
      Runtime: java11
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
